# Generated by Django 2.2.5 on 2019-12-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_todoitem_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='old_priority',
        ),
    ]
